# Generated by Django 5.2 on 2025-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='tasks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
