# Generated by Django 5.2 on 2025-05-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_checkin_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='user',
            new_name='employee',
        ),
    ]
